Update `FileLock` constructor to accept `pathlib.Path`
tox-dev/filelock pull request #110
Opened 2021-10-22 10:53 UTC by f-koehler

This is a small fix for people who employ `pathlib.Path` for their path handling. It allows a `Path` object to be passed to the constructor of `FileLock`. It is then converted to a normal `str` when storing it inside the object leaving the rest of the library unaffected.

2021-10-22 11:07 UTC, gaborbernat requested changes
Test and changelog? 😊

2021-10-22 11:48 UTC, f-koehler commented
> Test and changelog? blush

I added a test using `pytest.mark.parametrize`. What are you referring to with "changelog" am I supposed to update some changelog file. Sorry if I am being stupid but I could not find any instructions in the repo/doc. Only the `docs/changelog.rst` file which I did not want to touch since you seem to be the only author of that.

So please let me know what's missing.

2021-10-22 12:43 UTC, gaborbernat commented
> Only the `docs/changelog.rst` file which I did not want to touch since you seem to be the only author of that.

That's the one. Ignore that in past only I've edited it.

2021-10-22 18:40 UTC, FFY00 requested changes
Can we please make it `os.PathLike` instead? It covers way more types and the implementation is mostly the same, you just replace `str()` with `os.fspath()`.

2021-10-23 21:04 UTC, f-koehler commented
@FFY00 and @gaborbernat, I will get to work on this next week.

2021-10-23 21:16 UTC, FFY00 commented
Sounds good, no worries :blush:

2021-10-26 17:39 UTC, gaborbernat requested changes

2021-10-26 17:39 UTC, gaborbernat commented on src/filelock/_api.py
> +        self._lock_file: str = os.fspath(lock_file)  # noqa: SC200
Please remove this noqa and fix it by adding to to the whitelist.txt.

2021-10-26 17:44 UTC, FFY00 approved these changes
This looks alright to me, thanks!

2021-10-29 09:51 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/82cee43ca40954e27af8e2c525f36946/tenor.gif)

2021-10-29 09:51 UTC, merged

2021-10-29 10:07 UTC, gaborbernat commented
https://pypi.org/project/filelock/3.3.2/ is now out