Bugfix/147
tox-dev/filelock pull request #213
Opened 2023-03-25 18:51 UTC by jahrules

changes to resolve the issues reported in https://github.com/tox-dev/py-filelock/issues/147

2023-03-25 20:34 UTC, gaborbernat requested changes
Please rebase on top of main.

2023-03-25 21:15 UTC, gaborbernat requested changes
Test please 🥺

2023-03-25 22:00 UTC, jahrules commented
> Test please pleading_face

The mocker module that you found was very helpful for this. Thanks.

2023-03-26 03:23 UTC, gaborbernat approved these changes

2023-03-26 03:29 UTC, merged