use fchmod
tox-dev/filelock pull request #214
Opened 2023-03-26 17:08 UTC by jfennick

I'm getting a TypeError when py-filelock calls os.chmod(). The problem occurs when using pypy3.9, but not python3.11  I'm running into this in the context of trying to install pre-commit, but the problem appears to be in py-filelock.

```
$ mamba create --name filelock
$ mamba activate filelock
$ pip install pypy "python<3.10"
$ pip install pre-commit
$ pre-commit
An unexpected error has occurred: CalledProcessError: command: ('/Users/jakefennick/mambaforge-pypy3/envs/filelock/bin/python3.9', '-mvirtualenv', '/Users/jakefennick/.cache/pre-commit/repocvpepigy/py_env-python3.9')
return code: 1
stdout:
    RuntimeError: failed to build image pip, wheel, setuptools because:
    Traceback (most recent call last):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
    
    Traceback (most recent call last):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
    
    Traceback (most recent call last):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/jakefennick/mambaforge-pypy3/envs/filelock/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
stderr: (none)
Check the log at /Users/jakefennick/.cache/pre-commit/pre-commit.log
```

https://docs.python.org/3/library/os.html#os.chmod

Although the documentation claims that os.chmod accepts both a path-like object as well as an integer file descriptor, it does not seem to work here. However, in this case we 100% know we have a file descriptor, so directly calling os.fchmod should always work.

2023-03-26 17:13 UTC, gaborbernat commented
cc @jahrules

2023-03-26 17:13 UTC, gaborbernat commented on src/filelock/_unix.py
> +                os.fchmod(fd, self._mode)
This will not work on windows 🤷

2023-03-26 17:16 UTC, jahrules commented
The docs claim that as of python 3.3 fchmod and chmod are equivalent.

But if using fchmod resolves some issue, it shouldn't be a problem.

https://docs.python.org/3/library/os.html?highlight=fchmod#os.fchmod

2023-03-26 20:55 UTC, jfennick commented
Note that (if this PR is correct) the CI failure is spurious.

https://results.pre-commit.ci/run/github/17098256/1679850526.TbItmJeCQ3eodvVdUw9VBw

2023-03-26 21:11 UTC, jahrules commented
> Note that (if this PR is correct) the CI failure is spurious.
> 
> https://results.pre-commit.ci/run/github/17098256/1679850526.TbItmJeCQ3eodvVdUw9VBw

you just need to add fchmod to the whitelist and it will pass.

2023-03-26 21:37 UTC, jfennick commented
> > Note that (if this PR is correct) the CI failure is spurious.
> > https://results.pre-commit.ci/run/github/17098256/1679850526.TbItmJeCQ3eodvVdUw9VBw
> 
> you just need to add fchmod to the whitelist and it will pass.

Done!

2023-03-26 22:54 UTC, gaborbernat requested changes
Let's add a test if they are not equivalent.

2023-03-26 23:00 UTC, jahrules commented
@jfennick have you confirmed that this change fixes your issue?

2023-03-26 23:01 UTC, jfennick commented
> Let's add a test if they are not equivalent.

Could you be more specific? I'm not sure what kind of a test you're looking for.

2023-03-26 23:01 UTC, jfennick commented
> @jfennick have you confirmed that this change fixes your issue?

Yes, this PR fixes the issue on my machine.

2023-03-26 23:12 UTC, jfennick commented
```
$ mamba create --name filelock_src
$ mamba activate filelock_src
$ mamba install pypy "python<3.10"
$ pip install pre-commit
$ pip install filelock@git+https://github.com/jfennick/py-filelock.git
$ pre-commit
[INFO] Installing environment for https://github.com/asottile/add-trailing-comma.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/pyupgrade.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/blacken-docs.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tox-dev/tox-ini-fmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tox-dev/pyproject-fmt.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/PyCQA/flake8.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check python ast.....................................(no files to check)Skipped
check builtin type constructor use...................(no files to check)Skipped
check docstring is first.............................(no files to check)Skipped
check for merge conflicts............................(no files to check)Skipped
check yaml...........................................(no files to check)Skipped
check toml...........................................(no files to check)Skipped
debug statements (python)............................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
pyupgrade............................................(no files to check)Skipped
isort................................................(no files to check)Skipped
black................................................(no files to check)Skipped
blacken-docs.........................................(no files to check)Skipped
rst ``code`` is two backticks........................(no files to check)Skipped
tox-ini-fmt..........................................(no files to check)Skipped
pyproject-fmt........................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
prettier.............................................(no files to check)Skipped
markdownlint.........................................(no files to check)Skipped
Check hooks apply to the repository..................(no files to check)Skipped
Check for useless excludes...........................(no files to check)Skipped
```

2023-03-26 23:15 UTC, gaborbernat commented
> > Let's add a test if they are not equivalent.
> 
> Could you be more specific? I'm not sure what kind of a test you're looking for.

A test that would replicate this issue in the CI and shows that this fix fixes it. Generally, you commit first to the test and then to the solution.

2023-03-26 23:17 UTC, gaborbernat commented
> Although the documentation claims that os.chmod accepts both a path-like object as well as an integer file descriptor, it does not seem to work here. However, in this case we 100% know we have a file descriptor, so directly calling os.fchmod should always work.

If this is a pypy issue, how come to our CI did not catch it? Also, if this is a pypy bug why are we fixing it in this codebase and not within pypy? Also, did you submit and link a pypy bug report? I'll not accept PRs that are fixing upstream issues without a very good reason.

2023-03-26 23:43 UTC, jahrules commented
> > Although the documentation claims that os.chmod accepts both a path-like object as well as an integer file descriptor, it does not seem to work here. However, in this case we 100% know we have a file descriptor, so directly calling os.fchmod should always work.
> 
> If this is a pypy issue, how come to our CI did not catch it? Also, if this is a pypy bug why are we fixing it in this codebase and not within pypy? Also, did you submit and link a pypy bug report? I'll not accept PRs that are fixing upstream issues without a very good reason.

I highly suspect that this is down the the OS or filesystem being used. I don't know enough about how the os module interacts with the OS functions to know which is more likely. 

@jfennick can you share what OS/filesystem you're using?

2023-03-27 00:14 UTC, jfennick commented
The only reason I can think of that it's failing on my machine and not the CI is that I'm on macos Ventura 13.2.1 and the CI has macos 12. My filesystem is the default Apple Filesystem APFS.

2023-03-27 02:39 UTC, TheMatt2 commented
While I don't see any issue with using `os.fchmod`, I can not replicate this bug.

What is the Pypy version? It should be 7.x.x something.
Here is the version string I get when setting up Mamba (in a Docker container)

```
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:13:01)
[PyPy 7.3.11 with GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> 
```

Considering Pypy is ["Python in Python"](https://github.com/mozillazg/pypy#pypy-python-in-python-implementation), perhaps this is an old Pypy version, and a compatibility bug in pypy?

2023-03-27 02:46 UTC, jfennick commented
Should be the latest and greatest:
```
$ pypy --version
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:19:00)
[PyPy 7.3.11 with GCC Clang 14.0.6]
```

2023-03-27 03:16 UTC, TheMatt2 commented
Strange.

Also, it turns out that that error message is not what you would expect from Python < 3.3 either.
The error Python 3.2 gives is as follows:

```
Python 3.2.6 (default, Mar 26 2023, 23:08:31) 
[GCC 11.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> fd = os.open("test", os.O_CREAT)
>>> os.chmod(fd, 0o644)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't convert 'int' object to str implicitly
>>> 
```

2023-03-27 03:33 UTC, jfennick commented
Very strange indeed:

```
(filelock) jakefennick$ python
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:19:00)
[PyPy 7.3.11 with GCC Clang 14.0.6] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> fd = os.open("test", os.O_CREAT)
>>>> os.chmod(fd, 0o644)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected str, bytes or os.PathLike object, not int
>>>> os.fchmod(fd, 0o644)
```

2023-03-27 03:45 UTC, TheMatt2 commented
I think you got a Pypy bug there... one way or the other...

```
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)
[PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> fd = os.open("test", os.O_CREAT)
>>>> os.chmod(fd, 0o644)
>>>> 

```

```
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:13:01)
[PyPy 7.3.11 with GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> fd = os.open("test", os.O_CREAT)
>>>> os.chmod(fd, 0o644)
>>>> 
```

2023-03-27 04:13 UTC, jfennick commented
Here's the relevant section from my os.py

```
    if _exists("statvfs") and _exists("fstatvfs"): # mac os x10.3
        _add("HAVE_FSTATVFS", "statvfs")
    supports_fd = _set

    _set = set()
    _add("HAVE_FACCESSAT",  "access")
    # Some platforms don't support lchmod().  Often the function exists
    # anyway, as a stub that always returns ENOSUP or perhaps EOPNOTSUPP.
    # (No, I don't know why that's a good design.)  ./configure will detect
    # this and reject it--so HAVE_LCHMOD still won't be defined on such
    # platforms.  This is Very Helpful.
    #
    # However, sometimes platforms without a working lchmod() *do* have
    # fchmodat().  (Examples: Linux kernel 3.2 with glibc 2.15,
    # OpenIndiana 3.x.)  And fchmodat() has a flag that theoretically makes
    # it behave like lchmod().  So in theory it would be a suitable
    # replacement for lchmod().  But when lchmod() doesn't work, fchmodat()'s
    # flag doesn't work *either*.  Sadly ./configure isn't sophisticated
    # enough to detect this condition--it only determines whether or not
    # fchmodat() minimally works.
    #
    # Therefore we simply ignore fchmodat() when deciding whether or not
    # os.chmod supports follow_symlinks.  Just checking lchmod() is
    # sufficient.  After all--if you have a working fchmodat(), your
    # lchmod() almost certainly works too.
    #
    # _add("HAVE_FCHMODAT",   "chmod")
    _add("HAVE_FCHOWNAT",   "chown")
    _add("HAVE_FSTATAT",    "stat")
    _add("HAVE_LCHFLAGS",   "chflags")
    _add("HAVE_LCHMOD",     "chmod")
    if _exists("lchown"): # mac os x10.3
        _add("HAVE_LCHOWN", "chown")
```

I'm not exactly sure what's going on here, but it sounds like the story around os.chmod isn't so simple. There's a lot of macos 10.3 specific logic here, so maybe they forgot to add similar logic for chmod.

Anyhow, I think the point of this PR is that why are we even giving pypy, etc the chance to mess this up? At this particular call site we 100% know for sure `fd` is an integer, so why call an unnecessarily general function? Why not minimize your attack surface?

2023-03-27 04:36 UTC, TheMatt2 commented
> I also tried your minimal reproducible example (albeit, in a Docker container), and could not reproduce the error.

Setup on an actual Mac.

I was able to replicate the error.

```
% mamba create --name filelock_src
% mamba activate filelock_src
% mamba install pypy "python<3.10"
% pip install pre-commit
% pip install filelock
$ git clone https://github.com/tox-dev/py-filelock.git
% pre-commit
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/asottile/add-trailing-comma.
[INFO] Initializing environment for https://github.com/asottile/pyupgrade.
[INFO] Initializing environment for https://github.com/PyCQA/isort.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs:black==23.1.
[INFO] Initializing environment for https://github.com/pre-commit/pygrep-hooks.
[INFO] Initializing environment for https://github.com/tox-dev/tox-ini-fmt.
[INFO] Initializing environment for https://github.com/tox-dev/pyproject-fmt.
[INFO] Initializing environment for https://github.com/PyCQA/flake8.
[INFO] Initializing environment for https://github.com/PyCQA/flake8:flake8-bugbear==23.3.12,flake8-comprehensions==3.11.1,flake8-pytest-style==1.7.2,flake8-spellcheck==0.28,flake8-unused-arguments==0.0.13,flake8-noqa==1.3.1,pep8-naming==0.13.3,flake8-pyproject==1.2.3.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier:prettier@2.7.1,@prettier/plugin-xml@2.2.
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/Guest/mambaforge/envs/filelock_src/bin/python3.9', '-mvirtualenv', '/Users/Guest/.cache/pre-commit/repok_yeqbq1/py_env-python3.9')
return code: 1
stdout:
    RuntimeError: failed to build image setuptools, wheel, pip because:
    Traceback (most recent call last):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
    
    Traceback (most recent call last):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
    
    Traceback (most recent call last):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 52, in _install
        with parent.non_reentrant_lock_for_key(wheel_img.name):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/contextlib.py", line 119, in __enter__
        return next(self.gen)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 146, in non_reentrant_lock_for_key
        with _CountedFileLock(str(self.path / f"{name}.lock")):
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 227, in __enter__
        self.acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/virtualenv/util/lock.py", line 29, in acquire
        super().acquire(timeout, poll_interval)
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_api.py", line 182, in acquire
        self._acquire()
      File "/Users/Guest/mambaforge/envs/filelock_src/lib/pypy3.9/site-packages/filelock/_unix.py", line 38, in _acquire
        os.chmod(fd, self._mode)
    TypeError: expected str, bytes or os.PathLike object, not int
stderr: (none)
Check the log at /Users/Guest/.cache/pre-commit/pre-commit.log
```

2023-03-27 04:37 UTC, gaborbernat commented
I'd like to notify the right people of their bug before we accept a temporary workaround on our side. So I'm holding this PR until we figure out how is this a problem and fill.in a bug issue there.

2023-03-27 04:53 UTC, jfennick commented
Excellent, sounds good to me. I can work off my fork in the meantime.

2023-03-27 05:14 UTC, TheMatt2 commented
I think I tracked down part of the issue.

The official Python docs [say](https://docs.python.org/3/library/os.html#os.chmod) that `os.chmod(fd, mode)` will work for Python > 3.2

Pypy, on the other hand, says the ability use a file descriptor "may be unavailable" https://foss.heptapod.net/pypy/pypy/-/blob/59ace91749d15ffc3b60510ae727de51e21f2728/pypy/module/posix/interp_posix.py#L1183-L1199

 ```
Change the access permissions of a file.

path may always be specified as a string.
On some platforms, path may also be specified as an open file descriptor.
  If this functionality is unavailable, using it raises an exception.
```

With the normal Pypy for MacOS, `os.chmod()` works as you would expect, but when Pypy is installed via Mamba, you see this error.

I note that the Python build information is `[PyPy 7.3.11 with GCC Clang 14.0.6]`. Normal python builds for MacOS (in my experience) either say "[Clang 14...]" or "[Clang Apple LLVM...]". I've never seen "GCC Clang".

So I guess an issue needs to be raised with Pypy that their `chmod()` does not fall back to always succeed, even if the platform does actually support it. Working out precisely _why_ this is happening... is still a bit beyond me.

I suspect the build server didn't catch it because it may be using micromamba, not the full distribution but I'm not sure.

2023-03-27 05:31 UTC, gaborbernat commented
I don't think we use mamba to provision Python. It uses the GitHub action. Can someone fill in an issue to pypy and link it?

2023-03-27 13:07 UTC, jahrules commented
done. 

https://foss.heptapod.net/pypy/pypy/-/issues/3908

2023-03-27 14:24 UTC, TheMatt2 commented
PYPY maintainers please read!!!

This issue applies to the version of pypy as installed in Anaconda on macOS according to the official installation instructions:

The native pypy build for MacOS seems unaffected.

https://www.pypy.org/posts/2022/11/pypy-and-conda-forge.html

```
(filelock) jakefennick$ python
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:19:00)
[PyPy 7.3.11 with GCC Clang 14.0.6] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import os
>>>> fd = os.open("test", os.O_CREAT)
>>>> os.chmod(fd, 0o644)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected str, bytes or os.PathLike object, not int
>>>> os.fchmod(fd, 0o644)
```

2023-03-27 14:54 UTC, gaborbernat approved these changes

2023-03-27 14:55 UTC, merged