Surprisingly simple fix to not working properly with Python threads in Windows
tox-dev/filelock pull request #219
Opened 2023-04-05 00:25 UTC by csm10495

Fixes #82

With this, i can successfully run on win32:

```
import tempfile
import pathlib
import threading
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from filelock import FileLock
import time
import logging

#log = logging.getLogger("filelock")
#log.setLevel(logging.DEBUG)
#log.addHandler(logging.StreamHandler())

TEST_FILE = pathlib.Path(tempfile.gettempdir()) / 'test_file.txt'
TEST_LOCK_FILE =  pathlib.Path(tempfile.gettempdir()) / 'test_file.txt.lock'
LOCK = FileLock(TEST_LOCK_FILE)

def test():
    with LOCK:
        assert TEST_FILE.read_text() == 'hi'
        TEST_FILE.write_text('')
        assert TEST_FILE.read_text() == ''
        TEST_FILE.write_text('hi')
        assert TEST_FILE.read_text() == 'hi'
        return True

if __name__ == '__main__':
    print(f"Test file: {TEST_FILE}")
    print(f"Test lock file: {TEST_LOCK_FILE}")
    TEST_FILE.write_text('hi')

    results = []

    # works with ProcessPoolExecutor but not with ThreadPoolExecutor
    # It also is more likely to work if we sleep after calling submit()
    with ThreadPoolExecutor(max_workers=256) as pool:
        for i in range(1000):
            if i % 10 == 0:
                print (f"Loop: {i+1}")
            results.append(pool.submit(test))

        for idx, result in enumerate(results):
            print (f"Checking result: {idx + 1}")
            assert result.result() == True
```

2023-04-05 03:24 UTC, gaborbernat commented
Making the lock thread local shouldn't be a default. Instead, you should consider your use case to attach the lock to a thread local variable.

2023-04-05 03:55 UTC, csm10495 commented
I'm curious though: Is there ever a case where this would break someone? I guess if someone expected the object to be the same across threads.. but then why would they be using the lock to begin with?

2023-04-05 04:07 UTC, gaborbernat commented
My worry is about backwards compatibility. What if today someone attaches the lock to a thread local object. Wouldn't this break those people? Before today you could have used a global variable to lock out threads, however, this change would move that functionality to the file system level. Which could be an issue if the lock type is a soft file.

2023-04-05 04:13 UTC, csm10495 commented
If they did that, they would have to have done something like this already:

```
local = threading.local()

def get_lock():
    local.LOCK = FileLock(TEST_LOCK_FILE)
    return local.LOCK
```

then use `get_lock()` inside the thread. This still works for me in my testing.

If they did something like this: 

```
local = threading.local()
local.LOCK = FileLock(TEST_LOCK_FILE)

def test():
    with local.LOCK:
```

either way (with this change or without it) they would get 
```
AttributeError: '_thread._local' object has no attribute 'LOCK'
```
from inside the thread (so they need to recreate it).

2023-04-05 04:37 UTC, gaborbernat commented
Okay, based on this I am willing to accept this tomorrow, however I would like you to stick around and handle any potential follow-up pull request that might be needed to address regressions introduced by this. Thank you

2023-04-05 04:40 UTC, csm10495 commented
Sure thing. If anything weird comes up, happy to help figure it out. (fingers crossed that it just works though :) )

2023-04-05 13:07 UTC, TheMatt2 commented
> I'm curious though: Is there ever a case where this would break someone? I guess if someone expected the object to be the same across threads.. but then why would they be using the lock to begin with?

I must agree that I can not think of a _reason_ this would break "someone". I'm concerned this will somehow break something somewhere, as is the nature of these things. Perhaps a major version up? (v3.11 or v4).

2023-04-05 13:17 UTC, TheMatt2 commented
Just pointing out. `BaseFileLock` already has an explicit `_thread_lock` that it uses to atomically change its rentrant count.
If you make `BaseFileLock` local, I believe this secondary lock can be removed completely.

https://github.com/tox-dev/py-filelock/blob/33c07264904bda9ee9369513e0f6ddcfbad13b10/src/filelock/_api.py#L170-L172

2023-04-05 13:21 UTC, gaborbernat requested changes
> If you make `BaseFileLock` local, I believe this secondary lock can be removed completely.

Let's make the CI also pass.

2023-04-05 15:14 UTC, TheMatt2 commented
For what it's worth, virtualenv already implements a custom wrapper around filelock to create this functionality.
And this change would not break virtualenv.

https://github.com/pypa/virtualenv/blob/0e4cad0e06668fbd93be6605c9a13f871ce647c7/src/virtualenv/util/lock.py#L13-L30

2023-04-05 18:50 UTC, gaborbernat approved these changes

2023-04-05 19:21 UTC, gaborbernat commented
@csm10495 seems pypy does not like it 🤔

2023-04-05 19:25 UTC, csm10495 commented
What went wrong? pre-commit looks ok. Have a log?

2023-04-05 19:28 UTC, gaborbernat commented
Check the CI those jobs just hang 🤷

2023-04-05 19:34 UTC, csm10495 commented
.. oh lol. I'll probably come back to it a bit later, will set up pypy in wsl to see.

2023-04-05 19:43 UTC, csm10495 commented
... uhh umm:

```
csm10495@csm10495-desk:~/pypy/pypy3.9-v7.3.11-linux64/bin $ ./pypy -m pip freeze
attrs==22.2.0
cffi==1.15.1
exceptiongroup==1.1.1
filelock @ file:///mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock
greenlet==0.4.13
hpy==0.0.4.dev179+g9b5d200
iniconfig==2.0.0
packaging==23.0
pluggy==1.0.0
pytest==7.2.2
pytest-mock==3.10.0
readline==6.2.4.1
tomli==2.0.1
csm10495@csm10495-desk:~/pypy/pypy3.9-v7.3.11-linux64/bin $ ./pypy -m pytest /mnt/c/Users/csm10495/Desktop/filelock_testing -vvv
===================================================================== test session starts ======================================================================platform linux -- Python 3.9.16[pypy-7.3.11-final], pytest-7.2.2, pluggy-1.0.0 -- /home/csm10495/pypy/pypy3.9-v7.3.11-linux64/bin/pypy
cachedir: .pytest_cache
rootdir: /mnt/c/Users/csm10495/Desktop/filelock_testing
plugins: mock-3.10.0
collected 56 items

../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_error.py::test_timeout_str PASSED                                    [  1%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_error.py::test_timeout_repr PASSED                                   [  3%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_error.py::test_timeout_lock_file PASSED                              [  5%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_error.py::test_timeout_pickle PASSED                                 [  7%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[UnixFileLock-str] PASSED                    [  8%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[UnixFileLock-PurePath] PASSED               [ 10%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[UnixFileLock-Path] PASSED                   [ 12%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[SoftFileLock-str] PASSED                    [ 14%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[SoftFileLock-PurePath] PASSED               [ 16%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_simple[SoftFileLock-Path] PASSED                   [ 17%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_ro_folder[UnixFileLock] PASSED                     [ 19%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_ro_folder[SoftFileLock] PASSED                     [ 21%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_ro_file[UnixFileLock] PASSED                       [ 23%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_ro_file[SoftFileLock] PASSED                       [ 25%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_missing_directory[UnixFileLock] PASSED             [ 26%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_missing_directory[SoftFileLock] PASSED             [ 28%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_context_manager[UnixFileLock] PASSED        [ 30%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_context_manager[SoftFileLock] PASSED        [ 32%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_acquire[UnixFileLock] PASSED                [ 33%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_acquire[SoftFileLock] PASSED                [ 35%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_forced_release[UnixFileLock] PASSED         [ 37%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_nested_forced_release[SoftFileLock] PASSED         [ 39%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_threaded_shared_lock_obj[UnixFileLock] PASSED      [ 41%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_threaded_shared_lock_obj[SoftFileLock] PASSED      [ 42%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_threaded_lock_different_lock_obj[UnixFileLock] PASSED [ 44%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_threaded_lock_different_lock_obj[SoftFileLock] PASSED [ 46%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_timeout[UnixFileLock] PASSED                       [ 48%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_timeout[SoftFileLock] PASSED                       [ 50%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_non_blocking[UnixFileLock] PASSED                  [ 51%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_non_blocking[SoftFileLock] PASSED                  [ 53%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_default_timeout[UnixFileLock] PASSED               [ 55%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_default_timeout[SoftFileLock] PASSED               [ 57%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_context_release_on_exc[UnixFileLock] PASSED        [ 58%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_context_release_on_exc[SoftFileLock] PASSED        [ 60%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_acquire_release_on_exc[UnixFileLock] PASSED        [ 62%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_acquire_release_on_exc[SoftFileLock] PASSED        [ 64%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_del[UnixFileLock] SKIPPED (del() does not trigger GC in PyPy) [ 66%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_del[SoftFileLock] SKIPPED (del() does not trigger GC in PyPy) [ 67%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_cleanup_soft_lock PASSED                           [ 69%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_poll_intervall_deprecated[UnixFileLock] PASSED     [ 71%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_poll_intervall_deprecated[SoftFileLock] PASSED     [ 73%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_context_decorator[UnixFileLock] PASSED             [ 75%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_context_decorator[SoftFileLock] PASSED             [ 76%]
../../../../../mnt/c/Users/csm10495/Desktop/filelock_testing/py-filelock/tests/test_filelock.py::test_lock_mode PASSED                                   [ 78%]
../../ [...]

2023-04-05 19:47 UTC, csm10495 commented
I can try to spinup a VM later to try a bit more in depth if we don't see something obvious

2023-04-05 19:52 UTC, gaborbernat commented
> Has it ever hung before?

Sometimes in the past, pypy is buggy 😆 we had to alter the code to support it.

2023-04-05 22:56 UTC, csm10495 commented
I spun-up an Ubuntu 20.04 LTS VM and still can't seem to get it to fail:

```
csm10495@csm10495-VirtualBox:~/pypy3.9-v7.3.11-linux64/bin/py-filelock$ ../pypy -m pytest 

================================================================ test session starts ================================================================

platform linux -- Python 3.9.16[pypy-7.3.11-final], pytest-7.2.2, pluggy-1.0.0

rootdir: /home/csm10495/pypy3.9-v7.3.11-linux64/bin/py-filelock

plugins: mock-3.10.0

collected 56 items                                                                                                                                  



tests/test_error.py ....                                                                                                                      [  7%]

tests/test_filelock.py ................................ss..................                                                                   [100%]



=========================================================== 54 passed, 2 skipped in 4.80s ===========================================================

csm10495@csm10495-VirtualBox:~/pypy3.9-v7.3.11-linux64/bin/py-filelock$ cat /etc/lsb-release 

DISTRIB_ID=Ubuntu

DISTRIB_RELEASE=22.04

DISTRIB_CODENAME=jammy

DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

csm10495@csm10495-VirtualBox:~/pypy3.9-v7.3.11-linux64/bin/py-filelock$ ../pypy --version

Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 14:23:21)

[PyPy 7.3.11 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]

csm10495@csm10495-VirtualBox:~/pypy3.9-v7.3.11-linux64/bin/py-filelock$ 


```

I'm running out of ideas to repro :/

2023-04-05 23:05 UTC, csm10495 commented
So this is kind of weird: If I use `--cov` it seems like it hangs. If I don't use `--cov` it seems to pass normally:

```
csm10495@csm10495-VirtualBox:~/pypy3.9-v7.3.11-linux64/bin/py-filelock$ ../pypy -m pytest --color=yes --junitxml /home/csm10495/pypy3.9-v7.3.11-linux64/bin/py-filelock/.tox/junit.py310.xml  -vvv --cov

================================================================ test session starts ================================================================

platform linux -- Python 3.9.16[pypy-7.3.11-final], pytest-7.2.2, pluggy-1.0.0 -- /home/csm10495/pypy3.9-v7.3.11-linux64/bin/pypy

cachedir: .pytest_cache

rootdir: /home/csm10495/pypy3.9-v7.3.11-linux64/bin/py-filelock

plugins: cov-4.0.0, mock-3.10.0

collected 56 items                                                                                                                                  



tests/test_error.py::test_timeout_str PASSED                                                                                                  [  1%]

tests/test_error.py::test_timeout_repr PASSED                                                                                                 [  3%]

tests/test_error.py::test_timeout_lock_file PASSED                                                                                            [  5%]

tests/test_error.py::test_timeout_pickle PASSED                                                                                               [  7%]

tests/test_filelock.py::test_simple[UnixFileLock-str] PASSED                                                                                  [  8%]

tests/test_filelock.py::test_simple[UnixFileLock-PurePath] PASSED                                                                             [ 10%]

tests/test_filelock.py::test_simple[UnixFileLock-Path] PASSED                                                                                 [ 12%]

tests/test_filelock.py::test_simple[SoftFileLock-str] PASSED                                                                                  [ 14%]

tests/test_filelock.py::test_simple[SoftFileLock-PurePath] PASSED                                                                             [ 16%]

tests/test_filelock.py::test_simple[SoftFileLock-Path] PASSED                                                                                 [ 17%]

tests/test_filelock.py::test_ro_folder[UnixFileLock] PASSED                                                                                   [ 19%]

tests/test_filelock.py::test_ro_folder[SoftFileLock] PASSED                                                                                   [ 21%]

tests/test_filelock.py::test_ro_file[UnixFileLock] PASSED                                                                                     [ 23%]

tests/test_filelock.py::test_ro_file[SoftFileLock] PASSED                                                                                     [ 25%]

tests/test_filelock.py::test_missing_directory[UnixFileLock] PASSED                                                                           [ 26%]

tests/test_filelock.py::test_missing_directory[SoftFileLock] PASSED                                                                           [ 28%]

tests/test_filelock.py::test_nested_context_manager[UnixFileLock] PASSED                                                                      [ 30%]

tests/test_filelock.py::test_nested_context_manager[SoftFileLock] PASSED                                                                      [ 32%]

tests/test_filelock.py::test_nested_acquire[UnixFileLock] PASSED                                                                              [ 33%]

tests/test_filelock.py::test_nested_acquire[SoftFileLock] PASSED                                                                              [ 35%]

tests/test_filelock.py::test_nested_forced_release[UnixFileLock] PASSED                                                                       [ 37%]

tests/test_filelock.py::test_nested_forced_release[SoftFileLock] PASSED                                                                       [ 39%]

tests/test_filelock.py::test_threaded_shared_lock_obj[UnixFileLock] 


```

2023-04-05 23:40 UTC, gaborbernat commented
I'd be ok to disable coverage reporting for pypy...

2023-04-05 23:52 UTC, csm10495 commented
Maybe? Let me try debugging it a tiny bit more later today. If I still have no idea, then yeah i guess disable.

2023-04-06 03:39 UTC, csm10495 commented
So it seems like if i downgrade coverage to something in the 6.X range it passed much faster.. though honestly I don't know what changed between 6.X and 7.X (or therefore if that type of change is valid). 

Also it doesn't quite hang.. but just goes really really slow. On my VM with 8 cores, it takes 214 seconds but passes on Ubuntu. The test it goes slow on wants 100 threads, though the GH action runners are 2-core iirc. I see a recent run took about 10 minutes on Mac against main (so without this change).

I'm not sure how to disable coverage on just pypy with the current setup. (I figure coverage is more/less the same on pypy vs cpython anyways so shouldn't really lose much). @gaborbernat can you push a change to disable cov on pypy (or let me know how). Thanks!

2023-04-06 03:46 UTC, TheMatt2 commented
For what its worth, `pytest -vvv --cov` (the current head prior to this PR) passes in 7.3 seconds on my Mac.
Am I missing something?

2023-04-06 03:46 UTC, csm10495 commented
@TheMatt2 with pypy?

2023-04-06 03:51 UTC, TheMatt2 commented
cpython. I'll test pypy in a sec

2023-04-06 04:00 UTC, csm10495 commented
@TheMatt2 Can you run the same pytest for pypy against this changeset instead of the one before it?

2023-04-06 04:10 UTC, TheMatt2 commented
Sure... oh interesting.

It failed in 56 seconds.

```
pypy3 -m pytest -vvv --cov
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.7.13[pypy-7.3.9-final], pytest-7.2.2, pluggy-1.0.0 -- /usr/local/bin/pypy3
cachedir: .pytest_cache
rootdir: .../py-filelock
plugins: timeout-2.1.0, mock-3.10.0, cov-4.0.0
collected 56 items                                                                                                                                                                                         

tests/test_error.py::test_timeout_str PASSED                                                                                                                                                         [  1%]
tests/test_error.py::test_timeout_repr PASSED                                                                                                                                                        [  3%]
tests/test_error.py::test_timeout_lock_file PASSED                                                                                                                                                   [  5%]
tests/test_error.py::test_timeout_pickle PASSED                                                                                                                                                      [  7%]
tests/test_filelock.py::test_simple[UnixFileLock-str] PASSED                                                                                                                                         [  8%]
tests/test_filelock.py::test_simple[UnixFileLock-PurePath] PASSED                                                                                                                                    [ 10%]
tests/test_filelock.py::test_simple[UnixFileLock-Path] PASSED                                                                                                                                        [ 12%]
tests/test_filelock.py::test_simple[SoftFileLock-str] PASSED                                                                                                                                         [ 14%]
tests/test_filelock.py::test_simple[SoftFileLock-PurePath] PASSED                                                                                                                                    [ 16%]
tests/test_filelock.py::test_simple[SoftFileLock-Path] PASSED                                                                                                                                        [ 17%]
tests/test_filelock.py::test_ro_folder[UnixFileLock] PASSED                                                                                                                                          [ 19%]
tests/test_filelock.py::test_ro_folder[SoftFileLock] PASSED                                                                                                                                          [ 21%]
tests/test_filelock.py::test_ro_file[UnixFileLock] PASSED                                                                                                                                            [ 23%]
tests/test_filelock.py::test_ro_file[SoftFileLock] PASSED                                                                                                                                            [ 25%]
tests/test_filelock.py::test_missing_directory[UnixFileLock] PASSED                                                                                                                                  [ 26%]
tests/test_filelock.py::test_missing_directory[SoftFileLock] PASSED                                                                                                                                  [ 28%]
tests/test_filelock.py::test_nested_context_manager[UnixFileLock] PASSED                                                                                                                             [ 30%]
tests/test_filelock.py::test_nested_context_manager[SoftFileLock] PASSED                                                                                                                             [ 32%]
tests/test_filelock.py::test_nested_acquire[UnixFileLock] PASSED                                                                                                                                     [ 33%]
tests/test_filelock.py::test_nested_acquire[SoftFileLock] PASSED                                                                                                                                     [ 35%]
tests/test_filelock.py::test_nested_forced_release[UnixFileLock] PASSED                                                                                                                              [ 37%]
tests/test_filelock.py::test_nested_forced_release[SoftFileLock] PASSED                                                                                                                              [ 39%]
tests/test_filelock.py::test_threaded_shared_lock_obj[UnixFileLock] PASSED                                                                                                                           [ 41%]
tests/test_filelock.py::test_threaded_shared_lock_obj[SoftFileLock] PASSED                                                                                                                           [ 42%]
tests/test_filelock.py::test_threaded_lock_different_lock_obj[UnixFileLock] PASSED                                                                                                                   [ 44%]
tests/test_filelock.py::test_threaded_lock_different_lock_obj[SoftFileLock] PASSED                                                                                                                   [ 46%]
tests/test_filelock.py::test_timeout[UnixFileLock] PASSED                                                                                                                                            [ 48%]
tests/test_filelock.py::test_timeout[SoftFileLock] PASSED                                                                                                                                            [ 50%]
tests/test_filelock.py::test_non_blocking[UnixFileLock] PASSED                                                                                                                                       [ 51%]
tests/test_filelock.py::test_non_blocking[SoftFileLock] PASSED                                                                                                                                       [ 53%]
tests/test_filelock.py::test_default_timeout[UnixFileLock] PASSED                                                                                                                                    [ 55%]
tests/test_filelock.py::test_default_timeout[SoftFileLock] PASSED                                                                                                                                    [ 57%]
tests/test_filelock.py::test_context_release_on_exc[UnixFileLock] PASSED                                                                                                                             [ 58%]
tests/test_filelock.py::test_context_release_on_exc[SoftFileLock] PASSED                                                                                                                             [ 60%]
tests/test_filelock.py::test_acquire_release_on_exc[UnixFileLock] PASSED                                                                                                                             [ 62%]
tests/test_filelock.py::test_acquire_release_on_exc[SoftFileLock] PASSED                                                                                                  [...]

2023-04-06 04:11 UTC, csm10495 commented
.. Well i didn't expect that at all. I get those failures when i forget to `pip install` my dev version (and instead the version from pypi ran).. any chance that happened here?

2023-04-06 04:25 UTC, TheMatt2 commented
> .. Well i didn't expect that at all. I get those failures when i forget to pip install my dev version (and instead the version from pypi ran).. any chance that happened here?

_(Slightly blushing)_ um... yep that's what happened. I installed the dev version, but I didn't realize the default filelock was already installed...

Let's try that again

2023-04-06 04:30 UTC, TheMatt2 commented
Code version in this PR

Pypy passed in 21.63 seconds

<details>

```
pypy3 -m pytest -vvv
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.7.13[pypy-7.3.9-final], pytest-7.2.2, pluggy-1.0.0 -- /usr/local/bin/pypy3
cachedir: .pytest_cache
rootdir: .../py-filelock
plugins: timeout-2.1.0, mock-3.10.0, cov-4.0.0
collected 56 items                                                                                                                                                                                         

tests/test_error.py::test_timeout_str PASSED                                                                                                                                                         [  1%]
tests/test_error.py::test_timeout_repr PASSED                                                                                                                                                        [  3%]
tests/test_error.py::test_timeout_lock_file PASSED                                                                                                                                                   [  5%]
tests/test_error.py::test_timeout_pickle PASSED                                                                                                                                                      [  7%]
tests/test_filelock.py::test_simple[UnixFileLock-str] PASSED                                                                                                                                         [  8%]
tests/test_filelock.py::test_simple[UnixFileLock-PurePath] PASSED                                                                                                                                    [ 10%]
tests/test_filelock.py::test_simple[UnixFileLock-Path] PASSED                                                                                                                                        [ 12%]
tests/test_filelock.py::test_simple[SoftFileLock-str] PASSED                                                                                                                                         [ 14%]
tests/test_filelock.py::test_simple[SoftFileLock-PurePath] PASSED                                                                                                                                    [ 16%]
tests/test_filelock.py::test_simple[SoftFileLock-Path] PASSED                                                                                                                                        [ 17%]
tests/test_filelock.py::test_ro_folder[UnixFileLock] PASSED                                                                                                                                          [ 19%]
tests/test_filelock.py::test_ro_folder[SoftFileLock] PASSED                                                                                                                                          [ 21%]
tests/test_filelock.py::test_ro_file[UnixFileLock] PASSED                                                                                                                                            [ 23%]
tests/test_filelock.py::test_ro_file[SoftFileLock] PASSED                                                                                                                                            [ 25%]
tests/test_filelock.py::test_missing_directory[UnixFileLock] PASSED                                                                                                                                  [ 26%]
tests/test_filelock.py::test_missing_directory[SoftFileLock] PASSED                                                                                                                                  [ 28%]
tests/test_filelock.py::test_nested_context_manager[UnixFileLock] PASSED                                                                                                                             [ 30%]
tests/test_filelock.py::test_nested_context_manager[SoftFileLock] PASSED                                                                                                                             [ 32%]
tests/test_filelock.py::test_nested_acquire[UnixFileLock] PASSED                                                                                                                                     [ 33%]
tests/test_filelock.py::test_nested_acquire[SoftFileLock] PASSED                                                                                                                                     [ 35%]
tests/test_filelock.py::test_nested_forced_release[UnixFileLock] PASSED                                                                                                                              [ 37%]
tests/test_filelock.py::test_nested_forced_release[SoftFileLock] PASSED                                                                                                                              [ 39%]
tests/test_filelock.py::test_threaded_shared_lock_obj[UnixFileLock] PASSED                                                                                                                           [ 41%]
tests/test_filelock.py::test_threaded_shared_lock_obj[SoftFileLock] PASSED                                                                                                                           [ 42%]
tests/test_filelock.py::test_threaded_lock_different_lock_obj[UnixFileLock] PASSED                                                                                                                   [ 44%]
tests/test_filelock.py::test_threaded_lock_different_lock_obj[SoftFileLock] PASSED                                                                                                                   [ 46%]
tests/test_filelock.py::test_timeout[UnixFileLock] PASSED                                                                                                                                            [ 48%]
tests/test_filelock.py::test_timeout[SoftFileLock] PASSED                                                                                                                                            [ 50%]
tests/test_filelock.py::test_non_blocking[UnixFileLock] PASSED                                                                                                                                       [ 51%]
tests/test_filelock.py::test_non_blocking[SoftFileLock] PASSED                                                                                                                                       [ 53%]
tests/test_filelock.py::test_default_timeout[UnixFileLock] PASSED                                                                                                                                    [ 55%]
tests/test_filelock.py::test_default_timeout[SoftFileLock] PASSED                                                                                                                                    [ 57%]
tests/test_filelock.py::test_context_release_on_exc[UnixFileLock] PASSED                                                                                                                             [ 58%]
tests/test_filelock.py::test_context_release_on_exc[SoftFileLock] PASSED                                                                                                                             [ 60%]
tests/test_filelock.py::test_acquire_release_on_exc[UnixFileLock] PASSED                                                                                                                             [ 62%]
tests/test_filelock.py::test_acquire_release_on_exc[SoftFileLock] PASSED                                                                                         [...]

2023-04-06 04:35 UTC, csm10495 commented
Phew. A pass with reasonable speed. Yeah I'm not sure why the hang is so long in ci.

2023-04-06 05:57 UTC, TheMatt2 commented
I've been unable to replicate the hang in pypy

2023-04-06 15:39 UTC, TheMatt2 commented
It seems the `test_threaded_lock_different_lock_obj` takes significantly longer depending on how many cores the computer has. It may be the ci servers have _lots_ of cores, which is causing the test to take a _long time_, but not actually hang. Is this possible?

If so, this could be prevented by reducing the number of concurrent threads and increasing how many lock acquires are done per thread:

https://github.com/csm10495/py-filelock/blob/902d659fc47b4e2ae941b5acd5281e08a8a17763/tests/test_filelock.py#L215-L220

2023-04-06 15:41 UTC, gaborbernat commented
> It may be the ci servers have _lots_ of cores,

Github actions VMs are always provisioned with 2 cores 🤔

2023-04-06 15:48 UTC, TheMatt2 commented
Well... so much for that theory.
In fairness, that link says the MacOS servers have 3 cores, which does explain why those are slower.

Though, the reason that `test_threaded_shared_lock_obj` is slower now is because this PR makes sure all threads grab the lock exclusively. Previously, multiple threads were able to all enter the lock together.

2023-04-06 16:08 UTC, gaborbernat commented
So I've put in https://github.com/tox-dev/py-filelock/pull/224, that will remove coverage reporting for pypy 👍

2023-04-06 16:36 UTC, TheMatt2 commented
Interesting. The prior CI with coverage Ubuntu was canceled due to time on `test_filelock.py::test_threaded_shared_lock_obj[SoftFileLock]`

MacOS was canceled due to time on `test_filelock.py::test_threaded_shared_lock_obj[UnixFileLock]`
(The CI report doesn't actually say, it only shows the last test that passed. But from testing it seems this would have been the test to go next)

The tests I ran yesterday on MacOS that completed in reasonable times were done using pypy 3.8

Is this a pypy 3.9 issue?

2023-04-06 16:49 UTC, TheMatt2 commented
Update

Ubuntu 22.10

Pypy 3.9

```
umask 022
git checkout origin/fix-windows-thread-locking
pypy3 -m pip uninstall filelock
pypy3 -m pip install ".[testing]"
rm -rf .coverage .pytest_cache **/__pycache__
time pypy3 -m pytest -vvv --cov
```

Test completed after 

```
real	26m33.687s
user	9m25.055s
sys	4m43.054s
```

So it seems that this can complete given enough time.
But it takes forever.

2023-04-06 16:56 UTC, csm10495 commented
That long with multiple cores. I think with just 2 in ci, it's suppppper slow.

2023-04-06 17:16 UTC, merged

2023-04-06 17:55 UTC, TheMatt2 commented
I know this is closed now. But I thought I would add the final set of timing results on MacOS.
In short, I can not reproduce the results taking so long.
(Is this going to be another crazy issue where Pypy behaves differently, depending on how it was compiled?)

2017 MacBook Air with 2 hyperthreaded cores

Test on Pypy 3.8: Finished with coverage in 47 seconds
```
Python 3.8.16 (a9dbdca6fc3286b0addd2240f11d97d8e8de187a, Dec 29 2022, 12:50:26)
[PyPy 7.3.11 with GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)] on darwin
filelock-0.1.dev238+ga2ccce3 (this PR)

rm -rf .coverage .pytest_cache **/__pycache__
time ../pypy3.8-v7.3.11-macos_x86_64/bin/pypy3 -m pytest -vvv --cov
...
======================================== 48 passed, 2 skipped in 47.15s =========================================
../pypy3.8-v7.3.11-macos_x86_64/bin/pypy3 -m pytest -vvv --cov  31.77s user 14.81s system 95% cpu 49.025 total
```

Test on Pypy 3.9: Finished with coverage in 54 seconds
```
Python 3.9.16 (feeb267ead3e6771d3f2f49b83e1894839f64fb7, Dec 29 2022, 15:36:58)
[PyPy 7.3.11 with GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)] on darwin
filelock-0.1.dev238+ga2ccce3

rm -rf .coverage .pytest_cache **/__pycache__
time ../pypy3.9-v7.3.11-macos_x86_64/bin/pypy3 -m pytest -vvv --cov
...
======================================== 54 passed, 2 skipped in 54.14s =========================================
../pypy3.9-v7.3.11-macos_x86_64/bin/pypy3 -m pytest -vvv --cov  37.11s user 16.40s system 94% cpu 56.440 total
```