Read/Write File Lock
tox-dev/filelock pull request #380
Opened 2024-11-23 02:32 UTC by Yard1

Currently WIP. Need to add asyncio API and more tests.

This PR adds a `ReadWriteFileLock` API and implementation (currently only for Unix. I don't know if this is possible on Windows). `ReadWriteFileLock` allows the caller to operate in either READ or WRITE mode. The lock can be held by multiple READers at the same time, but a WRITEr is guaranteed to have exclusive access to the lock (across both READers and WRITErs). The lock is writer-preferred by employing an outer and inner lock (with the outer serving as staging for acquiring the inner - this means the outer lock is much easier to acquire) - while this seems to be working well in practice, there are no actual guarantees of ordering and priority.

Closes #307

2024-12-01 21:19 UTC, Yard1 commented
@gaborbernat This is ready for review now. Happy to iterate on the API if needed (especially the Wrapper part, I think it's a bit clunky, though perhaps all it needs is just a rename).

2024-12-01 22:03 UTC, gaborbernat commented
The CI is failing.

2024-12-02 00:26 UTC, Yard1 commented
Thanks, will fix the type issues. Aside from that, I see the Windows tests are failing with
> FAIL Required test coverage of 76.0% not reached. Total coverage: 66.65%

Considering there is no Windows implementation here, can you advise on how to deal with this?

2024-12-02 15:13 UTC, gaborbernat commented
I see a lot of markers to ignore typing errors. This is not the right approach. We should make the typing correct, not ignore the errors generated.

2024-12-02 23:40 UTC, Yard1 commented
Thanks - I'm still iterating on this. Will mark as draft until I am done.

2024-12-03 00:05 UTC, Yard1 commented
In general the current way the async APIs are implemented necessitates ignores. I would like to avoid breaking changes, but it seems quite challenging to fix that otherwise (and I wouldn't want to do this in this PR anyway).

2024-12-03 00:26 UTC, antoni-openai commented
I think I've managed to get rid of most of the added type ignores (as well as the sphinx nitpick ignores). The ones that remain should be consistent with rest of the codebase.

2024-12-03 00:28 UTC, Yard1 commented
I think I managed to get rid of most of the added type ignores (and the sphinx nitpick ignores). The ones that remain + linter noqas should be consistent with the rest of the codebase.

2024-12-03 05:38 UTC, gaborbernat commented
> I think I managed to get rid of most of the added type ignores (and the sphinx nitpick ignores). The ones that remain + linter noqas should be consistent with the rest of the codebase.

Thank you, heads up that I will be unavailable until the new year, so I will not be able to accept this change request until then.

2025-01-03 01:45 UTC, gaborbernat requested changes
```
tests/test_read_write_filelock.py: 15 warnings
  /home/runner/work/filelock/filelock/.tox/3.9/lib/python3.9/site-packages/filelock/read_write/_api.py:265: RuntimeWarning: coroutine 'BaseAsyncReadWriteFileLock.release' was never awaited
    self.release(force=True)
```

You will need to fix this warning. Also, the Windows test fail because the coverage thershold is not reached 🤔 You will need to use the windows pragma no cover to satisfy the CI.

cc @Yard1

2025-01-12 21:49 UTC, Yard1 commented
@gaborbernat thanks, let me take a look at that!

2025-01-13 18:04 UTC, gaborbernat commented
@Yard1 still failing.

2025-01-13 18:15 UTC, Yard1 commented
Yep, will keep iterating. Marking as draft until done, will ping!

2025-02-04 00:12 UTC, gaborbernat commented
@Yard1 seems it's stalled we can reopen when you restart work on it.

2025-02-04 00:12 UTC, closed without merging

2025-02-04 00:49 UTC, Yard1 commented
Thanks, hoping to get to it next weekend.