Handle Unwritable Path
tox-dev/filelock pull request #47
Opened 2019-01-12 19:53 UTC by ooglek

## Description

If the OS cannot open a file because the path is bad, it does not make sense to repeatedly attempt to open the file as it will continue to fail, indefinitely if the `-1` default timeout is used, without any feedback to the user.

This modifies the behavior to raise the OSError/IOError exception received on Windows or Unix so FileLock exits rather than a futile infinite loop that will never succeed.

Tests are written to demonstrate the behavior.

2019-03-25 02:19 UTC, benediktschmitt commented
Thank you!
I merged your pull request and made some changes to SoftFileLock: https://github.com/benediktschmitt/py-filelock/tree/ooglek-handle-unwritable-path

I can only run tests on linux at the moment, so I'd appreciate any feedback for other systems.

2020-02-06 10:47 UTC, mcsimps2 commented
@benediktschmitt I don't see these changes in master and it still seems to be a problem in the latest pip release #60

2020-02-21 16:22 UTC, hmeine commented
I am very much interested in this fix. Indeed, we had two situations (after switching from a different lock implementation to filelock) in which SoftFileLock would just hang:
* a read-only filesystem
* a non-existant directory
In both cases, one would expect an exception to be raised that allows to discriminate from an existing lock file.

2021-09-27 08:32 UTC, gaborbernat requested changes
Can you please rebase it on the latest main? You'll need to add some tests for it too, Thanks!

2021-09-27 12:00 UTC, ooglek commented
I included a test for the change in the original pull request 2+ years ago. Hopefully it should suffice.

2021-09-27 12:05 UTC, gaborbernat commented
Oh missed that, still needs a rebase though 😊

2021-09-27 15:54 UTC, ooglek commented
@mcsimps2 @hmeine My need for this passed 2 years ago. One of you or someone you know will need to carry on this one-line change if you want it in a release.

2021-09-27 18:34 UTC, FFY00 commented
I rebased the PR.

2021-09-27 22:55 UTC, gaborbernat requested changes
We'll need to fix the tests and linting 👍

2021-09-27 22:59 UTC, FFY00 commented
Yes, I had a look and the issues seem to be false positives (unless my english is rusty and there is actually a typo in words flagged).

2021-09-28 10:04 UTC, gaborbernat commented
Superseded by https://github.com/tox-dev/py-filelock/pull/96

2021-09-28 10:04 UTC, closed without merging