Replace logger().info with logger().debug
tox-dev/filelock pull request #74
Opened 2020-07-06 08:13 UTC by moi90

For users of the library, the information if a lock was acquired is rather "debug" than "info" severity.

2021-09-27 08:30 UTC, gaborbernat requested changes
Can you please rebase it on the latest main? You'll need to add some tests for it too, Thanks!

2021-09-27 09:17 UTC, moi90 commented
Given that no testing infrastructure is currently available for logging in the project, the work required to implement this is much more involved than these two changed words. I'm not interested in doing this work and I kindly ask you to refrain from this demand.

2021-09-27 09:56 UTC, gaborbernat commented
Wasn't a demand just a request for merge. We can make this blocked then on migration to pytest.

2021-09-28 09:47 UTC, gaborbernat commented
Superseded by https://github.com/tox-dev/py-filelock/pull/95

2021-09-28 09:47 UTC, closed without merging

2021-10-04 11:55 UTC, moi90 commented
Thanks, this is very much appreciated!